stages:
  - deploy

deploy_ansible:
  stage: deploy
  image: python:3.10
  tags:
    - docker
  script:
    # Install required tools
    - pip install pyyaml requests

    # Convert vars.yml to extra_vars.json
    - |
      python3 <<EOF
      import yaml, json
      with open('vars.yml') as f:
          vars_yaml = yaml.safe_load(f)
      with open('extra_vars.json', 'w') as f:
          json.dump(vars_yaml, f)
      EOF

    # Trigger AAP job template
    - |
      echo "Triggering AAP job template..."
      response=$(curl -sk -X POST "https://aap.rydzinski.local/api/controller/v2/job_templates/9/launch/" \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer $AAP_TOKEN" \
        -d @extra_vars.json)

      # Print the response to help diagnose issues
      echo "Response from AAP: $response"

      job_id=$(echo "$response" | python3 -c "import sys, json; print(json.load(sys.stdin).get('job', ''))")

      if [[ -z "$job_id" ]]; then
        echo "❌ Failed to get job ID from AAP response. Response was: $response"
        exit 1
      fi

      echo "✅ AAP Job ID: $job_id"

    # Poll AAP job status
    - |
      while true; do
        status=$(curl -sk "https://aap.rydzinski.local/api/controller/v2/jobs/$job_id/" \
          -H "Authorization: Bearer $AAP_TOKEN" | python3 -c "import sys, json; print(json.load(sys.stdin)['status'])")

        echo "Current AAP job status: $status"

        if [[ "$status" == "successful" ]]; then
          echo "Job completed successfully!"
          break
        elif [[ "$status" == "failed" ]]; then
          echo "Job failed!"
          exit 1
        fi

        sleep 5
      done
