---
- name: test play
  hosts: all
  gather_facts: no
  vars:
    #ANSIBLE_REMOTE_TEMP: /exports/home/
    #ANSIBLE_KEEP_REMOTE_FILES: 1
    deployment_remote_tmp: "{{ lookup('env', 'HOME')}}/.ansible/tmp"
    deployment_location: "{{ lookup('env', 'HOME')}}/syntheticdata"
  tasks:
    - name: Check hostname
      ansible.builtin.command: hostname

    - name: Find files called woody
      ansible.builtin.find:
        path: "{{ deployment_location }}"
        patterns: "ansible-tmp*" 
        file_type: type
      register: files_to_delete

    - name: Print the file
      ansible.builtin.debug:
        msg: "{{ item.path }}"
      loop: "{{ files_to_delete }}"

    - name: Stat the file
      ansible.builtin.stat:
        path: /tmp/testfile.txt
      register: file_check

    - debug:
        var: file_check.stat

    - name: Show all received extra vars
      ansible.builtin.copy:
        src: /tmp/testfile.txt 
        dest: "{{ deployment_location }}" 
        remote_src: yes
         
