---
- name: Try and replicate the permissions issue
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Show all received extra vars
      ansible.builtin.copy:
        src: /tmp/testfile.txt 
        dest: /exports/home/
         
