---
- name: test play
  hosts: all
  gather_facts: no
  vars:
    ANSIBLE_REMOTE_TEMP: /exports/home/
    ANSIBLE_KEEP_REMOTE_FILES: 1
  tasks:
    - name: Check hostname
      ansible.builtin.command: hostname

    - name: Stat the file
      ansible.builtin.stat:
        path: /tmp/testfile.txt
      register: file_check

    - debug:
        var: file_check.stat

    - name: Show all received extra vars
      ansible.builtin.copy:
        src: /tmp/testfile.txt 
        dest: /export/home/
        remote_src: yes
         
